# permissions for end users to view environments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: environment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: myoperator
    app.kubernetes.io/part-of: myoperator
    app.kubernetes.io/managed-by: kustomize
  name: environment-viewer-role
rules:
- apiGroups:
  - env.code.operator.com
  resources:
  - environments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - env.code.operator.com
  resources:
  - environments/status
  verbs:
  - get
