---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - env.code.operator.com
  resources:
  - environments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - env.code.operator.com
  resources:
  - environments/finalizers
  verbs:
  - update
- apiGroups:
  - env.code.operator.com
  resources:
  - environments/status
  verbs:
  - get
  - patch
  - update
